-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQghD99pnHyVsHRuPRJ
SqH0FVmRSMbqioS1rTpYKNWEfrGgCgYIKoZIzj0DAQehRANCAARg0f5XvIF9LJN/
SlokZS7tgkGmnEtofdWrnc5G6RVfkP8hACeqgJnMiNomZJemITH/R9jAqanPy06U
kifW0Kni
-----END PRIVATE KEY-----